In [1]:
import numpy as np
import pandas as pd 
import sqlite3
import requests

from tqdm import tqdm
from xml.etree import ElementTree
from IPython.display import HTML

from pprint import pprint

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [2]:
#!pip install openpyxl
#!pip install tqdm
#!pip install tabulate

In [3]:
# !proxyon

In [32]:
# Run in /nfs/zefys (takes roughly 24 hours!)
# !find ./ -wholename "*/presentation/*.jpg" -o -wholename "*/presentation/*.jpeg" -o -wholename "*/presentation/*.png" > ~/SPUNK/workbench/zefys_image_files.txt

In [5]:
!ls

README.md  statistics.html  statistics.md  workbench  zefys-statistics.ipynb

In [6]:
!pwd

/nfs/git-annex/kai.labusch/SPUNK/SPUNK

In [7]:
df_all = pd.read_csv('workbench/zefys_image_files.txt')

In [8]:
df = df_all.loc[~df_all.fullpath.str.startswith('./scandata') & ~df_all.fullpath.str.startswith('./_tosort')].copy() # remove scandata files since they do not follow the schema

In [9]:
df[['zdb', 'year', 'month', 'day', 'issue']]= df.fullpath.str.extract('./[publish/]*([^/]+)/([^/]+)/([^/]+)/([^/]+)/([^/]+)/.*')

In [10]:
df = df.dropna()

In [11]:
df[['zdb']] = df.zdb.str.extract('([^_]+).*')

In [12]:
df[['page','type']] = df.fullpath.str.extract('.*?([0-9]+).(png|jpg|jpeg|tif)$')

In [13]:
df.page = df.page.astype(int)

df = df.loc[df.page > 0]

df.issue = df.issue.astype(int)

In [14]:
df.shape

(6462694, 8)

In [15]:
df_meta=[]
for _, (zdb,count) in tqdm(pd.DataFrame(df.zdb.value_counts().reset_index()).iterrows()):
    zdb_id = zdb[0:-1] + "-" +  zdb[-1:]

    url = "https://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&query=zdbid={}&recordSchema=oai_dc".format(zdb_id)

    response = requests.get(url, stream=True)

    response.raw.decode_content = True

    events = ElementTree.iterparse(response.raw)

    meta = {"zdb": zdb, "title": "", "creator": "", "publisher": "", "date": "", "language": ""}

    for event, elem in events:
        # print(elem.tag, elem.text)

        if elem.tag=="{http://purl.org/dc/elements/1.1/}title":
            meta["title"]= elem.text
            continue

        if elem.tag=="{http://purl.org/dc/elements/1.1/}creator":
            meta["creator"]= elem.text
            continue

        if elem.tag=="{http://purl.org/dc/elements/1.1/}publisher":
            meta["publisher"]= elem.text
            continue

        if elem.tag=="{http://purl.org/dc/elements/1.1/}date":
            meta["date"]= elem.text
            continue

        if elem.tag=="{http://purl.org/dc/elements/1.1/}language":
            meta["language"]= elem.text
            continue
            
    df_meta.append(meta)
    
    # break

df_meta = pd.DataFrame(df_meta)

216it [00:23,  9.16it/s]

In [16]:
df_meta.title = df_meta.title.str.extract('([^:]*).*?')

In [17]:
df_tmp = df_meta.merge(df, on='zdb')

In [18]:
df_tmp.shape

(6462694, 13)

In [19]:
df_list = pd.DataFrame(df_tmp.zdb.value_counts()).reset_index()
df_list["cumsum"] = df_list["count"].cumsum()
df_list=df_list[["count", "cumsum", "zdb"]].merge(df_meta, on="zdb")

In [20]:
df_list

,count,cumsum,zdb,title,creator,publisher,date,language
0,706544,706544,24353991,Königlich privilegirte Berlinische Zeitung von Staats- und gelehrten Sachen,"Fontane, Theodor [Mitwirkender]",Berlin : Voss. Erben,1827-1911,ger
1,641669,1348213,2436020X,Berliner Börsen-Zeitung,,Berlin : Metzold,1857-1939,ger
2,612275,1960488,27646518,Berliner Tageblatt und Handels-Zeitung,"Tergit, Gabriele [Mitwirkender]",Berlin : Mosse,1872-1932,ger
3,310273,2270761,24340492,National-Zeitung,,Berlin : Die Expedition der National-Zeitung,1848-1910,ger
4,291734,2562495,30744556,Tägliche Rundschau,,Berlin : Zeitungsverlag Schmidt-Dumont & Co.,1881-1922,ger
5,281899,2844394,2719372X,Berliner Morgenpost,,Berlin : Ullstein,1898-1933,ger
6,254113,3098507,27913090,Berlinische Nachrichten von Staats- und gelehrten Sachen,,Berlin : Haude & Spener,1740-1872,ger
7,203312,3301819,30743977,Deutsche Tageszeitung,,Berlin : Dt. Tageszeitung AG,1894-1920,ger
8,195156,3496975,3074409X,Der Tag,,Berlin : Scherl,1901-1921,ger
9,181813,3678788,26120215,Berliner Zeitung Online-Archiv,,Berlin : Berliner Verl.,1945-1990,ger
10,180255,3859043,30744064,Der Reichsbote,,Berlin : Der Reichsbote,1873-1934,ger
11,179451,4038494,30744088,Staatsbürger-Zeitung,,Berlin : Grunert (Druck: Berlin : Schloßdruckerei G.m.b.H.),1865-1920,ger
12,179363,4217857,27112366,Vossische Zeitung,"Tergit, Gabriele [Chefredakteur]",Berlin : Ullstein,1911-1934,ger
13,169868,4387725,27971740,Berliner Volkszeitung,,Berlin : Dt. Verl.,1904-1930,ger
14,168578,4556303,2812988X,Königsberger Hartungsche Zeitung,,Königsberg : [Verlag nicht ermittelbar],1858-1924,ger
15,138676,4694979,30740459,Berliner Morgen-Zeitung,,Berlin : Mosse,1891-1920,ger
16,136422,4831401,28028685,Norddeutsche allgemeine Zeitung,,Berlin : Norddt. Buchdruckerei u. Verl.-Anst.,1878-1904,ger
17,135948,4967349,30740484,Berliner Neueste Nachrichten,,Berlin : Wolff,1889-1919,ger
18,135584,5102933,2612273X,Neue Zeit Online-Archiv,Christlich-Demokratische Union,Berlin : Verl. Neue Zeit,1945-1994,ger
19,119863,5222796,2532889X,Neues Deutschland Online-Archiv,"Spickermann, Wolfgang [Mitwirkender]",Berlin : Neues Deutschland,1946-1990,ger
20,114809,5337605,30744015,Deutsche Zeitung,,Berlin : Verl. Dt. Zeitung,1896-1919,ger
21,111754,5449359,27974534,Volks-Zeitung,"Mehring, Franz [Mitwirkender]",Berlin : Gutenberg-Dr. u. Verl.,1856-1904,ger
22,93378,5542737,27825061,Breslauer Zeitung,,"Breslau : Grass, Barth",1828-1917,ger
23,74193,5616930,3074040X,Berliner Abendpost,,Berlin : Ullstein,1889-1921,ger
24,53534,5670464,3074359X,Das deutsche Blatt,,Berlin : Schwiering,1891-1908,ger
25,50916,5721380,25128437,Teltower Kreisblatt,,Berlin : [Verlag nicht ermittelbar],1856-1944,ger
26,45546,5766926,28409322,Briesetal-Bote,,Birkenwerder : [Verlag nicht ermittelbar],1902-1943,ger
27,44267,5811193,2807323X,[Deutsche allgemeine Zeitung <Berlin>] ; Deutsche allgemeine Zeitung,,Berlin : Norddt. Buch-Dr. u. Verl.-Ges.,1919-1930,ger
28,35206,5846399,24332471,Berliner Gerichts-Zeitung,,Berlin : Behrend,1853-1898,ger
29,32532,5878931,31740595,Putlitzer Nachrichten,,Putlitz : Emil Völcker,1925-1941,ger
30,31679,5910610,28113159,[Deutsche allgemeine Zeitung <Berlin> / Ausgabe Groß-Berlin] ; Deutsche allgemeine Zeitung,,Berlin : Schmidt-Dumont,1922-1930,ger
31,29876,5940486,30744945,Ostpreußische Zeitung,,Königsberg : Schultzsche Hofbuchdruckerei,1851-1898,ger
32,27250,5967736,24329435,Deutsch-chinesische Nachrichten,,Tientsin : [Verlag nicht ermittelbar],1930-1939,ger
33,20265,5988001,26824620,Görlitzer Anzeiger,Görlitz,Görlitz : Jungandreas,1818-1868,ger
34,19381,6007382,28029094,Der Oberschlesische Wanderer,,Gleiwitz : Neumann,1833-1936,ger
35,17966,6025348,24352111,[Die rote Fahne <Berlin>] ; Die rote Fahne,"Liebknecht, Karl [Begründer]",[Wechselnde Erscheinungsorte] : [Verlag nicht ermittelbar],1918-1933,ger
36,16352,6041700,24360788,Türkische Post,,Istanbul : [Verlag nicht ermittelbar],1926-1943,ger
37,15397,6057097,27230028,Rul',,Berlin : Ullstein,1920-1931,rus
38,14877,6071974,27434114,Rheinsberger Zeitung,,Rheinsberg : Thurmann,1912-1942,ger
39,13956,6085930,2686518X,Schwedter Tageblatt,,Schwedt : [Verlag nicht ermittelbar],1925-1941,ger
40,13503,6099433,27443449,Sorauer Tageblatt,,Sorau : Rauert & Pittius,1923-1944,ger
41,13404,6112837,23820457,Deutsch-Ostafrikanische Zeitung,,Morogoro : v. Roy,1899-1916,ger
42,13234,6126071,26822829,Fehrbelliner Zeitung,Fehrbellin,Fehrbellin : [Verlag nicht ermittelbar],1925-1941,ger
43,12812,6138883,27450028,Baruther Anzeiger,,Baruth : Särchen,1925-1942,ger
44,12315,6151198,30743540,Spenersche Zeitung,,Berlin : Haude & Spener,1872-1874,ger
45,10413,6161611,26822246,Dziennik Berliński,,Berlin : Zeitung,1914-1939,pol
46,8117,6169728,24332690,Lähner Anzeiger,,Lähn : [Verlag nicht ermittelbar],1906-1919,ger
47,8058,6177786,2773674X,Pillauer Merkur,,Pillau : [Verlag nicht ermittelbar],1870-1913,ger
48,7430,6185216,27058621,Deutsches Nachrichtenbüro,Deutsches Nachrichtenbüro Berlin,"München : Deutsches Nachrichtenbüro, Hauptstelle München",1936-1940,ger
49,7408,6192624,24337511,Neustädter Kreisblatt,Neustadt Oberschlesien,"Neustadt, O.S. : [Verlag nicht ermittelbar]",1852-1911,ger
50,7140,6199764,24350382,Neue preußische Zeitung,,Berlin : Heinicke,1857-1893,ger
51,7131,6206895,24353243,Lokomotive an der Oder,,Oels : [Verlag nicht ermittelbar],1862-1883,ger
52,6346,6213241,24319697,Anzeiger für das Havelland,,Spandau : [Verlag nicht ermittelbar],1905-1908,ger
53,5744,6218985,25548839,[Pommersche Zeitung / Groß-Stettin] ; Pommersche Zeitung; Groß-Stettin,,Stettin : Pommerscher Zeitungsverl.,1934-1945,ger
54,5610,6224595,26373300,Zeitbilder,,Berlin : Ullstein,1918-1934,ger
55,5448,6230043,27479857,Leipziger Zeitungen,,[Leipzig] : [Verlag nicht ermittelbar],1737-1789,ger
56,5414,6235457,27246632,Goldaper Kreisblatt,Kreis Goldap,Goldap : [Verlag nicht ermittelbar],1908-1929,ger
57,5400,6240857,29096352,Urwähler-Zeitung,"Bernstein, Aaron [Chefredakteur]",Berlin : Heymanns,1849-1852,ger
58,5227,6246084,24324218,Frankensteiner Kreisblatt,Kreis Frankenstein Schlesien,Frankenstein : Lonsky,1877-1896,ger
59,5156,6251240,11614109,Neueste Mittheilungen,,Berlin : Klee,1882-1894,ger
60,5075,6256315,25546545,Reichswart,,Berlin : Verl. Der Reichswart,1920-1936,ger
61,4993,6261308,24327256,Groß-Wartenberger Kreisblatt,Kreis Groß Wartenberg,Groß-Wartenberg : Große,1908-1925,ger
62,4841,6266149,26824255,Greifenhagener Kreiszeitung,Landkreis Greifenhagen,Greifenhagen : Kundler,1915-1921,ger
63,4839,6270988,24350059,Osthavelländisches Kreisblatt,,Nauen : Freyhoff,1849-1892,ger
64,4621,6275609,26822441,Ermländische Zeitung,,Braunsberg : Wichert,1902-1905,ger
65,4499,6280108,24328558,Spandauer Zeitung,,Spandau : Stückrath,1925-1933,ger
66,4008,6284116,24329836,Die Feder,,Berlin : Hirschfeld,1898-1917,ger
67,3665,6287781,2682436X,Guhrauer Anzeiger an der Schlesisch-Posener Grenze,,Guhrau : Geschäftsstelle des Guhrauer Anzeigers,1915-1917,ger
68,3635,6291416,31219299,The Egyptian gazette,,Alexandria : [Verlag nicht ermittelbar],1890-1892,eng
69,3543,6294959,27960353,Neue Breslauer Zeitung,,"Breslau : Graß, Barth und Comp.",1820-1822,ger
70,3526,6298485,28864116,Senftenberger Anzeiger,,Ruhland : [Verlag nicht ermittelbar],1932-1933,ger
71,3526,6302011,26372939,[Die Voss / Wochen-Auslands-Ausgabe] ; Die Voss; Wochen-Auslands-Ausgabe,,Berlin : Ullstein,1921-1925,ger
72,3461,6305472,24336117,Münsterberger Kreisblatt,Kreis Münsterberg,Münsterberg : [Verlag nicht ermittelbar] (Druck: Münsterberg : Troedel),1888-1931,ger
73,3445,6308917,26836294,Neue Vetschauer Zeitung,,Vetschau : Gönnel,1902-1944,ger
74,3323,6312240,9838247,Provinzial-Correspondenz,,Berlin : Decker,1863-1884,ger
75,3277,6315517,26264894,Südwest,,Swakopmund [u.a.] : Kindt,1910-1914,ger
76,3143,6318660,27184833,Berliner Lokal-Anzeiger,,Berlin : Scherl,1910-1929,ger
77,3093,6321753,2436065X,"Danziger Dampfboot für Geist, Humor, Satire, Poesie, Welt- und Volksleben, Korrespondenz, Kunst, Literatur und Theater / Hrsg.","Schumacher, Wilhelm [Herausgeber]",Danzig : Gerhard,1833-1834,ger
78,3002,6324755,27760364,Oberschlesische Zeitung,,Beuthen : [Verlag nicht ermittelbar],1904-1933,ger
79,2936,6327691,24372006,Zabrzer Kreis-Blatt,Kreis Zabrze,Zabrze : [Verlag nicht ermittelbar],1907-1915,ger
80,2934,6330625,27478324,[Allgemeine Zeitung <München>] ; Allgemeine Zeitung,"Cotta, Johann Friedrich von [Mitwirkender]",München : Allg. Zeitung,1798-1925,ger
81,2896,6333521,26264699,Leipziger neueste Nachrichten und Handelszeitung,,Leipzig : Herfurth,1943-1945,ger
82,2833,6336354,27260112,Koschminer Zeitung und Anzeiger für die Städte Borek und Pogorzela,,Koschmin : H. Tuch,1909-1918,ger
83,2807,6339161,27116967,Kolmarer Kreisblatt,Kolmar in Posen,Kolmar : [Verlag nicht ermittelbar],1885-1897,ger
84,2806,6341967,28450747,Deutsche Nachrichten in Griechenland,,Athen : [Verlag nicht ermittelbar],1942-1944,ger
85,2723,6344690,27239494,Nakanune,,Berlin : [Verlag nicht ermittelbar],1922-1924,rus
86,2712,6347402,27254410,"Sorauer Wochenblatt für Unterhaltung, Belehrung und Ereignisse der Gegenwart",,Sorau : Rauert,1817-1846,ger
87,2659,6350061,26264882,Neue Wogen der Zeit,,Danzig : Schroth,1870-1878,ger
88,2647,6352708,24323688,Deutsche Zeitung in Nordchina = Dewen-ribao,,Tientsin : [Verlag nicht ermittelbar],1939-1941,ger
89,2582,6355290,27665847,Berliner Börsen-Courier,"Tergit, Gabriele [Mitwirkender]",Berlin : Berl. Börsen-Courier,1885-1895,ger
90,2555,6357845,27259006,Amtliches Kreisblatt für den Kreis Koschmin,Koschmin,Koschmin : H. Tuch,1909-1918,ger
91,2508,6360353,24347784,Argentinisches Wochenblatt = Semanario argentino,,Buenos Aires : Alemann,1942-1946,ger
92,2461,6362814,27246863,Gumbinner Kreisblatt,Kreis Gumbinnen,Gumbinnen : [Verlag nicht ermittelbar],1908-1943,ger
93,2453,6365267,24325259,Groß-Strehlitzer Kreisblatt,Groß-Strehlitz,Groß-Strehlitz : [Verlag nicht ermittelbar],1893-1926,ger
94,2412,6367679,2432291X,Bütower Anzeiger,,Bütow : Meyer,1889-1918,ger
95,2348,6370027,2718366X,Kolmarer Kreiszeitung,,Kolmar : [Verlag nicht ermittelbar],1900-1918,ger
96,2206,6372233,24344771,,,,,
97,2155,6374388,27457837,[Rheinsberger Zeitung / Illustrierte Beilage] ; Rheinsberger Zeitung; Illustrierte Beilage,,Rheinsberg : Thurmann,1926-1931,ger
98,2130,6376518,26824814,Görlitzer Fama,,Görlitz : Dreßler,1842-1849,ger
99,2096,6378614,27193615,Kölnische Zeitung,,Köln : DuMont Schauberg,1803-1945,ger
100,2059,6380673,25543817,Die Redaktion,"Wrede, Richard [Mitwirkender]",Berlin : Wrede,1902-1916,ger
101,2022,6382695,28922190,Oderberger Zeitung und Wochenblatt,,Oderberg : Feistel,1929-1929,ger
102,1972,6384667,2700319X,Hannoverscher Kurier,,Hannover : [Verlag nicht ermittelbar],1854-1944,ger
103,1959,6386626,24359476,Gewissen,,Potsdam : Wohlfahrtsbüro,1919-1929,ger
104,1952,6388578,24329307,Tilsiter allgemeine Zeitung,,Tilsit : Mauderode,1914-1917,ger
105,1948,6390526,26858137,Oberlausitzische Fama,,Görlitz : Nendel,1824-1827,ger
106,1946,6392472,27881386,Gumbinner allgemeine Zeitung,,Gumbinnen : [Verlag nicht ermittelbar],1943-1944,ger
107,1862,6394334,2708081X,Grünberger Wochenblatt,,Grünberg : Levysohn,1857-1863,ger
108,1838,6396172,27194772,Novoe slovo,,Berlin : [Verlag nicht ermittelbar],1941-1944,rus
109,1820,6397992,24335794,Neustettiner Kreisblatt,Neustettin,Neustettin : [Verlag nicht ermittelbar],1862-1869,ger
110,1708,6399700,29377559,Züllichauer wöchentliche Nachrichten,,Züllichau : Zwarr,1833-1843,ger
111,1696,6401396,26687665,al- Mu'aiyad,,al-Qāhira : Mukātabāt al-mu'ayyad,1896-1898,ara
112,1676,6403072,25545413,Die literarische Praxis,,Berlin : [Verlag nicht ermittelbar],1901-1910,ger
113,1671,6404743,24368568,Pressedienst des Generalgouvernements / Pressechef der Regierung des Generalgouvernements,Polen,Krakau : [Verlag nicht ermittelbar],1940-1943,ger
114,1667,6406410,24327438,Habelschwerdter Kreisblatt,,Habelschwerdt : Groeger,1843-1909,ger
115,1647,6408057,24378574,[Türkische Post / Halbmonatliche Wirtschaftsausgabe] ; Türkische Post,,Istanbul : [Verlag nicht ermittelbar],1938-1941,ger
116,1596,6409653,27510451,Extract der eingelauffenen Nouvellen,,[Leipzig] : [Verlag nicht ermittelbar],1700-1750,ger
117,1583,6411236,26823408,Greifenhagener Kreisblatt,Landkreis Greifenhagen,Stettin : Greßmann (Druck: Schwedt : Oesterreich),1844-1850,ger
118,1448,6412684,27848978,Tsingtauer neueste Nachrichten = Qingdao-xinbao,,Tsingtau : Tsingtauer Zeitungsges.,1904-1914,ger
119,1424,6414108,24337778,Strehlener Stadtblatt,Strehlen Breslau,Brieg : Falch,1835-1843,ger
120,1408,6415516,24372031,Zabrzer (Hindenburger) Kreisblatt = Zabrski (Hindenburgski) ore̜downik powiatowy,Kreis Hindenburg,Hindenburg : [Verlag nicht ermittelbar],1915-1926,ger
121,1383,6416899,27195491,Deutsches Volksecho,"Heym, Stefan [Mitwirkender]","New York, NY : Pastorius",1937-1939,ger
122,1366,6418265,32084511,Cüstriner Bürgerfreund,,Cüstrin : Nigmann,1839-1839,ger
123,1362,6419627,24377168,Holzmindisches Wochenblatt,,Holzminden : [Verlag nicht ermittelbar],1785-1792,ger
124,1354,6420981,28192515,"Zeitung auß Deutschlandt, Welschlandt, Franckreich, Böhmen, Hungarn, Niederlandt und andern Orten","Frischmann, Veit [Herausgeber]",Berlin : Runge,1618-1620,ger
125,1324,6422305,24336816,Sprottauer Wochenblatt,,Sprottau : Raabe,1839-1846,ger
126,1302,6423607,24365245,Münsterberger Wochenblatt,,Münsterberg : Kurts,1840-1848,ger
127,1269,6424876,27217693,Charlottenburger Zeitung,,Charlottenburg : Hanke,1880-1897,ger
128,1208,6426084,26264080,Berlinische privilegirte Zeitung,"Rüdiger, Johann Andreas [Verlag] [Vertrieb]",Berlin : Johann Andreas Rüdiger,1724-1753,ger
129,1157,6427241,2434073X,Der niederschlesische Anzeiger,,Glogau : [Verlag nicht ermittelbar],1821-1826,ger
130,1137,6428378,24324905,Frankensteiner Wochenblatt,,Frankenstein : Ulke,1836-1842,ger
131,1130,6429508,26866043,Stettiner General-Anzeiger,,Stettin : [Verlag nicht ermittelbar],1936-1937,ger
132,1110,6430618,24336609,Rybniker Kreisblatt,Kreis Rybnik,Rybnik : [Verlag nicht ermittelbar] (Druck: Gleiwitz : Neumann [[1842-1845]]),1842-1914,ger
133,1092,6431710,28326167,Kreisblatt des Königl. Preuss. Landraths-Amtes Preuss. Holland,Preußisch Holland,Elbing : [Verlag nicht ermittelbar],1833-1879,ger
134,1071,6432781,28173867,Leipziger Westend-Zeitung,,Leipzig-Plagwitz : E. Stephan,1896-1896,ger
135,1020,6433801,28421401,Zeitgeschehen im Wochenbild,,[Erscheinungsort nicht ermittelbar] : [Verlag nicht ermittelbar],2015-2015,ger
136,1003,6434804,24332616,Buckower Lokal-Anzeiger,Buckow (Märk. Schweiz),Buckow : Sirch,1933-1934,ger
137,961,6435765,28423215,BZ am Mittag,,Berlin : Berliner Verl.,1929-1929,ger
138,948,6436713,27259985,Amtliches Kreisblatt und Anzeiger für den Kreis und die Stadt Koschmin,Koschmin,Koschmin : H. Tuch,1905-1909,ger
139,942,6437655,2723969X,Ragniter Kreisblatt,Kreis Ragnit,Ragnit : Mügge,1882-1886,ger
140,925,6438580,28192898,Zeitung so im ... Jahr von Wochen zu Wochen colligirt und zusammen getragen worden,"Frischmann, Veit [Herausgeber]",Berlin : Runge,1622-1624,ger
141,916,6439496,25540695,"Intelligenzblatt für die Städte Oels, Bernstadt, Juliusburg, Hundsfeld und Festenberg",,Oels : [Verlag nicht ermittelbar],1856-1859,ger
142,900,6440396,28029240,Oberschlesien im Bild,,Gleiwitz : Neumann,1924-1936,ger
143,894,6441290,27191503,Aegyptische Nachrichten,,Kairo : [Verlag nicht ermittelbar],1912-1912,egy
144,824,6442114,26825326,Muskauer Wochenblatt,,Görlitz : [Verlag nicht ermittelbar],1821-1824,ger
145,804,6442918,25990202,Locomotive,"Held, Friedrich Wilhelm Alexander [Mitwirkender]",Berlin : F. Reichardt,1848-1848,ger
146,795,6443713,26264833,[Der Leuchtthurm <Leipzig>] ; Der Leuchtthurm,,Leipzig : Keil,1848-1850,ger
147,785,6444498,27185217,Der Anzeiger,,Ronneburg : Schumann,1799-1802,ger
148,760,6445258,3074491X,Die konstitutionelle Monarchie,,Königsberg : Schultzsche Hofbuchdruckerei,1850-1850,ger
149,746,6446004,26373257,Die Post aus Deutschland,,Berlin : Ullstein,1925-1927,ger
150,731,6446735,27191023,Neuer Görlitzer Anzeiger,,Görlitz : [Verlag nicht ermittelbar],1803-1808,ger
151,711,6447446,24328327,Tilsiter Zeitung,,Tilsit : Reyländer,1894-1914,ger
152,705,6448151,27443577,Sorauer Kreisblatt,Kreis Sorau,Sorau : Rauert,1843-1847,ger
153,686,6448837,24340649,Königsberger allgemeine Zeitung,,Königsberg : [Verlag nicht ermittelbar],1942-1942,ger
154,638,6449475,3159590X,Tageblatt für den Kreis Schlochau,,Preußisch Friedland : [Verlag nicht ermittelbar],1923-1925,ger
155,630,6450105,24348090,Hüben und drüben,,Buenos Aires : Alemann,1942-1946,ger
156,629,6450734,24335642,M,,Münsterberg : Kurts,1836-1939,ger
157,608,6451342,23913964,[Berliner Zeitung <Berlin>] ; Berliner Zeitung,,"Dayton, Ohio : LexisNexis",1994,ger
158,581,6451923,27239640,Ragniter Kreis-Anzeiger,Kreis Ragnit,Ragnit : Mügge,1882-1895,ger
159,556,6452479,28192710,Zeitung im ... Jhaar einkommen und wöchentlich zusammen getragen worden,"Frischmann, Veit [Herausgeber]",Berlin : Runge,1622-1622,ger
160,553,6453032,24347450,Vremja,,Berlin : [Verlag nicht ermittelbar],1921-1924,rus
161,505,6453537,24376619,Seelower Tageblatt,Seelow,Seelow : [Verlag nicht ermittelbar],1943-1943,ger
162,465,6454002,2433781X,Strehlener Kreis- und Stadtblatt,Strehlen Breslau,Brieg : Falch,1844-1846,ger
163,464,6454466,27452311,[Rheinsberger Zeitung / Illustrierte Unterhaltungsbeilage] ; Rheinsberger Zeitung; Illustrierte Unterhaltungsbeilage,,Rheinsberg : Thurmann,1925-1926,ger
164,455,6454921,28192552,Bericht waß sich zugetragen unnd begeben,"Frischmann, Veit [Herausgeber]",Berlin : Runge,1620-1621,ger
165,447,6455368,27193500,Les nouvelles Egyptiennes,,Kairo : [Verlag nicht ermittelbar],1912-1912,fre
166,411,6455779,31595868,Schlopper Tageblatt,,"Schloppe : Druck u. Verlag d. Schlopper Tageblatts, vorm. L. Schulz",1925-1925,ger
167,376,6456155,24367898,Preußische Zeitung,,"Königsberg, Pr. : Sturmverl.",1944-1944,ger
168,373,6456528,24323445,Der Beobachter an der Weichsel,,Pleß : Feistel,1806-1806,ger
169,368,6456896,27237795,Naš mir,,Berlin : [Verlag nicht ermittelbar],1924-1925,rus
170,320,6457216,28420743,Der praktische Landwirt im Briesetal,,Neudamm : Neumann,2015-2015,ger
171,276,6457492,27809250,Heimat und Ferne / hrsg. unter Mitwirkung d. Heimatmuseums-Vereins Kreis Teltow,,Berlin : [Verlag nicht ermittelbar],1933-1935,ger
172,271,6457763,24367424,Stadt- und Wochenblatt,,Münsterberg : Kurts (Druck: (Münsterberg) : (J. Troedel)),1848-1849,ger
173,269,6458032,28145781,"Bericht was sich zu anfang dieß itzt angehenden ... Jahres in Deutschlandt, Franckreich, Welschlandt, Böhmen, Ungern, Nederlandt und in andern örten hin unnd wieder zugetragen","Frischmann, Christoph [Herausgeber]",Berlin : Runge,1617-1618,ger
174,268,6458300,27809432,Unser Teltow / hrsg. unter Mitwirkung d. Heimatmuseums-Vereins Kreis Teltow,,Berlin : [Verlag nicht ermittelbar],1935-1939,ger
175,248,6458548,27809493,Sonntagsruhe,,Berlin : [Verlag nicht ermittelbar],1932-1934,ger
176,237,6458785,27248689,Severnoe slovo,,Revel' : Ostland-Pressevertrieb,1942-1943,rus
177,224,6459009,28036414,Idel-Ural,,Berlin : [Verlag nicht ermittelbar],1943-1944,tat
178,218,6459227,27352882,Kornblumen,,Charlottenburg : Pinthus,1880-1897,ger
179,208,6459435,27300729,Niederlausitzischer Anzeiger,,Sorau : Rauert,1816-1816,ger
180,192,6459627,27724633,Der Brummbär,,Berlin : Ullstein,1933-1933,ger
181,180,6459807,26268966,Deutsche Reichs-Bremse,,Leipzig : Keil,1849,ger
182,173,6459980,25543635,Deutsche Schriftsteller-Zeitung,,Berlin : [Verlag nicht ermittelbar],1910-1910,ger
183,172,6460152,28234182,[Supreme Headquarters Allied Expeditionary Force / Fallschirm-Ausgabe] ; Supreme Headquarters Allied Expeditionary Force,Allied Forces / Supreme Headquarters,[Erscheinungsort nicht ermittelbar] : [Verlag nicht ermittelbar],1945-1945,ger
184,162,6460314,2435367X,Gazavat,,Berlin : [Verlag nicht ermittelbar],1943-1944,rus

In [21]:
print(df_list.to_markdown())

|     |   count |   cumsum | zdb          | title                                                                                                                                                                           | creator                                          | publisher                                                                     | date      | language   |
|----:|--------:|---------:|:-------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------|:------------------------------------------------------------------------------|:----------|:-----------|
|   0 |  706544 |   706544 | 24353991     | Königlich privilegirte Berlinische Zeitung von Staats- und gelehrten Sachen                                                                                                     | Fontane, Theodor [Mitwirkender]                  | Berlin : Voss. Erben                                                          | 1827-1911 | ger        |
|   1 |  641669 |  1348213 | 2436020X     | Berliner Börsen-Zeitung                                                                                                                                                         |                                                  | Berlin : Metzold                                                              | 1857-1939 | ger        |
|   2 |  612275 |  1960488 | 27646518     | Berliner Tageblatt und Handels-Zeitung                                                                                                                                          | Tergit, Gabriele [Mitwirkender]                  | Berlin : Mosse                                                                | 1872-1932 | ger        |
|   3 |  310273 |  2270761 | 24340492     | National-Zeitung                                                                                                                                                                |                                                  | Berlin : Die Expedition der National-Zeitung                                  | 1848-1910 | ger        |
|   4 |  291734 |  2562495 | 30744556     | Tägliche Rundschau                                                                                                                                                              |                                                  | Berlin : Zeitungsverlag Schmidt-Dumont & Co.                                  | 1881-1922 | ger        |
|   5 |  281899 |  2844394 | 2719372X     | Berliner Morgenpost                                                                                                                                                             |                                                  | Berlin : Ullstein                                                             | 1898-1933 | ger        |
|   6 |  254113 |  3098507 | 27913090     | Berlinische Nachrichten von Staats- und gelehrten Sachen                                                                                                                        |                                                  | Berlin : Haude & Spener                                                       | 1740-1872 | ger        |
|   7 |  203312 |  3301819 | 30743977     | Deutsche Tageszeitung                                                                                                                                                           |                                                  | Berlin : Dt. Tageszeitung AG                                                  | 1894-1920 | ger        |
|   8 |  195156 |  3496975 | 3074409X     | Der Tag                                                                                                                                                                         |                                                  | Berlin : Scherl                                                               | 1901-1921 | ger        |
|   9 |  181813 |  3678788 | 26120215     | Berliner Zeitung Online-Archiv                                                                                                                                                  |                                                  | Berlin : Berliner Verl.                                                       | 1945-1990 | ger        |
|  10 |  180255 |  3859043 | 30744064     | Der Reichsbote                                                                                                                                                                  |                                                  | Berlin : Der Reichsbote                                                       | 1873-1934 | ger        |
|  11 |  179451 |  4038494 | 30744088     | Staatsbürger-Zeitung                                                                                                                                                            |                                                  | Berlin : Grunert (Druck: Berlin : Schloßdruckerei G.m.b.H.)                   | 1865-1920 | ger        |
|  12 |  179363 |  4217857 | 27112366     | Vossische Zeitung                                                                                                                                                               | Tergit, Gabriele [Chefredakteur]                 | Berlin : Ullstein                                                             | 1911-1934 | ger        |
|  13 |  169868 |  4387725 | 27971740     | Berliner Volkszeitung                                                                                                                                                           |                                                  | Berlin : Dt. Verl.                                                            | 1904-1930 | ger        |
|  14 |  168578 |  4556303 | 2812988X     | Königsberger Hartungsche Zeitung                                                                                                                                                |                                                  | Königsberg : [Verlag nicht ermittelbar]                                       | 1858-1924 | ger        |
|  15 |  138676 |  4694979 | 30740459     | Berliner Morgen-Zeitung                                                                                                                                                         |                                                  | Berlin : Mosse                                                                | 1891-1920 | ger        |
|  16 |  136422 |  4831401 | 28028685     | Norddeutsche allgemeine Zeitung                                                                                                                                                 |                                                  | Berlin : Norddt. Buchdruckerei u. Verl.-Anst.                                 | 1878-1904 | ger        |
|  17 |  135948 |  4967349 | 30740484     | Berliner Neueste Nachrichten                                                                                                                                                    |                                                  | Berlin : Wolff                                                                | 1889-1919 | ger        |
|  18 |  135584 |  5102933 | 2612273X     | Neue Zeit Online-Archiv                                                                                                                                                         | Christlich-Demokratische Union                   | Berlin : Verl. Neue Zeit                                                      | 1945-1994 | ger        |
|  19 |  119863 |  5222796 | 2532889X     | Neues Deutschland Online-Archiv                                                                                                                                                 | Spickermann, Wolfgang [Mitwirkender]             | Berlin : Neues Deutschland                                                    | 1946-1990 | ger        |
|  20 |  114809 |  5337605 | 30744015     | Deutsche Zeitung                                                                                                                                                                |                                                  | Berlin : Verl. Dt. Zeitung                                                    | 1896-1919 | ger        |
|  21 |  111754 |  5449359 | 27974534     | Volks-Zeitung                                                                                                                                                                   | Mehring, Franz [Mitwirkender]                    | Berlin : Gutenberg-Dr. u. Verl.                                               | 1856-1904 | ger        |
|  22 |   93378 |  5542737 | 27825061     | Breslauer Zeitung                                                                                                                                                               |                                                  | Breslau : Grass, Barth                                                        | 1828-1917 | ger        |
|  23 |   74193 |  5616930 | 3074040X     | Berliner Abendpost                                                                                                                                                              |                                                  | Berlin : Ullstein                                                             | 1889-1921 | ger        |
|  24 |   53534 |  5670464 | 3074359X     | Das deutsche Blatt                                                                                                                                                              |                                                  | Berlin : Schwiering                                                           | 1891-1908 | ger        |
|  25 |   50916 |  5721380 | 25128437     | Teltower Kreisblatt                                                                                                                                                             |                                                  | Berlin : [Verlag nicht ermittelbar]                                           | 1856-1944 | ger        |
|  26 |   45546 |  5766926 | 28409322     | Briesetal-Bote                                                                                                                                                                  |                                                  | Birkenwerder : [Verlag nicht ermittelbar]                                     | 1902-1943 | ger        |
|  27 |   44267 |  5811193 | 2807323X     | [Deutsche allgemeine Zeitung <Berlin>] ; Deutsche allgemeine Zeitung                                                                                                            |                                                  | Berlin : Norddt. Buch-Dr. u. Verl.-Ges.                                       | 1919-1930 | ger        |
|  28 |   35206 |  5846399 | 24332471     | Berliner Gerichts-Zeitung                                                                                                                                                       |                                                  | Berlin : Behrend                                                              | 1853-1898 | ger        |
|  29 |   32532 |  5878931 | 31740595     | Putlitzer Nachrichten                                                                                                                                                           |                                                  | Putlitz : Emil Völcker                                                        | 1925-1941 | ger        |
|  30 |   31679 |  5910610 | 28113159     | [Deutsche allgemeine Zeitung <Berlin> / Ausgabe Groß-Berlin] ; Deutsche allgemeine Zeitung                                                                                      |                                                  | Berlin : Schmidt-Dumont                                                       | 1922-1930 | ger        |
|  31 |   29876 |  5940486 | 30744945     | Ostpreußische Zeitung                                                                                                                                                           |                                                  | Königsberg : Schultzsche Hofbuchdruckerei                                     | 1851-1898 | ger        |
|  32 |   27250 |  5967736 | 24329435     | Deutsch-chinesische Nachrichten                                                                                                                                                 |                                                  | Tientsin : [Verlag nicht ermittelbar]                                         | 1930-1939 | ger        |
|  33 |   20265 |  5988001 | 26824620     | Görlitzer Anzeiger                                                                                                                                                              | Görlitz                                          | Görlitz : Jungandreas                                                         | 1818-1868 | ger        |
|  34 |   19381 |  6007382 | 28029094     | Der Oberschlesische Wanderer                                                                                                                                                    |                                                  | Gleiwitz : Neumann                                                            | 1833-1936 | ger        |
|  35 |   17966 |  6025348 | 24352111     | [Die rote Fahne <Berlin>] ; Die rote Fahne                                                                                                                                      | Liebknecht, Karl [Begründer]                     | [Wechselnde Erscheinungsorte] : [Verlag nicht ermittelbar]                    | 1918-1933 | ger        |
|  36 |   16352 |  6041700 | 24360788     | Türkische Post                                                                                                                                                                  |                                                  | Istanbul : [Verlag nicht ermittelbar]                                         | 1926-1943 | ger        |
|  37 |   15397 |  6057097 | 27230028     | Rul'                                                                                                                                                                            |                                                  | Berlin : Ullstein                                                             | 1920-1931 | rus        |
|  38 |   14877 |  6071974 | 27434114     | Rheinsberger Zeitung                                                                                                                                                            |                                                  | Rheinsberg : Thurmann                                                         | 1912-1942 | ger        |
|  39 |   13956 |  6085930 | 2686518X     | Schwedter Tageblatt                                                                                                                                                             |                                                  | Schwedt : [Verlag nicht ermittelbar]                                          | 1925-1941 | ger        |
|  40 |   13503 |  6099433 | 27443449     | Sorauer Tageblatt                                                                                                                                                               |                                                  | Sorau : Rauert & Pittius                                                      | 1923-1944 | ger        |
|  41 |   13404 |  6112837 | 23820457     | Deutsch-Ostafrikanische Zeitung                                                                                                                                                 |                                                  | Morogoro : v. Roy                                                             | 1899-1916 | ger        |
|  42 |   13234 |  6126071 | 26822829     | Fehrbelliner Zeitung                                                                                                                                                            | Fehrbellin                                       | Fehrbellin : [Verlag nicht ermittelbar]                                       | 1925-1941 | ger        |
|  43 |   12812 |  6138883 | 27450028     | Baruther Anzeiger                                                                                                                                                               |                                                  | Baruth : Särchen                                                              | 1925-1942 | ger        |
|  44 |   12315 |  6151198 | 30743540     | Spenersche Zeitung                                                                                                                                                              |                                                  | Berlin : Haude & Spener                                                       | 1872-1874 | ger        |
|  45 |   10413 |  6161611 | 26822246     | Dziennik Berliński                                                                                                                                                              |                                                  | Berlin : Zeitung                                                              | 1914-1939 | pol        |
|  46 |    8117 |  6169728 | 24332690     | Lähner Anzeiger                                                                                                                                                                 |                                                  | Lähn : [Verlag nicht ermittelbar]                                             | 1906-1919 | ger        |
|  47 |    8058 |  6177786 | 2773674X     | Pillauer Merkur                                                                                                                                                                 |                                                  | Pillau : [Verlag nicht ermittelbar]                                           | 1870-1913 | ger        |
|  48 |    7430 |  6185216 | 27058621     | Deutsches Nachrichtenbüro                                                                                                                                                       | Deutsches Nachrichtenbüro Berlin                 | München : Deutsches Nachrichtenbüro, Hauptstelle München                      | 1936-1940 | ger        |
|  49 |    7408 |  6192624 | 24337511     | Neustädter Kreisblatt                                                                                                                                                           | Neustadt Oberschlesien                           | Neustadt, O.S. : [Verlag nicht ermittelbar]                                   | 1852-1911 | ger        |

In [31]:
with open("statistics.md", "w") as f:
    f.write(df_list.to_markdown())

In [22]:
df_list_html = df_list.to_html(index=False, border=2)

html_template = f"""
<html>
<head>
    <style>
        table {{
            width: 60%;
            border-collapse: collapse;
            margin: 20px auto;
        }}
        th, td {{
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }}
        th {{
            background-color: #4CAF50;
            color: white;
        }}
        tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}
    </style>
</head>
<body>
    {df_list_html}
</body>
</html>
"""


with open("statistics.html", "w") as f:
    f.write(html_template)

In [23]:
df_rest = df_meta.merge(df.zdb.value_counts(), left_on='zdb', right_index=True, how='right')
df_rest = df_rest.loc[df_rest.title.isnull()][['zdb','count']].reset_index(drop=True)
df_rest

Empty DataFrame
Columns: [zdb, count]
Index: []

In [24]:
df_rest['count'].sum()

np.int64(0)

In [25]:
pd.DataFrame(df_tmp.type.value_counts())

        count
type
jpg   5953395
png    509299

In [26]:
df_tmp['url'] = "https://content.staatsbibliothek-berlin.de/zefys/SNP" + df_tmp.zdb + "-" + df_tmp.year + df_tmp.month + df_tmp.day + "-" + (df_tmp.issue - 1).astype(str) + "-" + df_tmp.page.astype(str) + "-0-0/full/full/0/default.jpg"

In [29]:
df_tmp.reset_index(drop=True).to_csv('workbench/zefys-files.tsv', sep='\t')

In [28]:
df_tmp.head(2887947).tail()

,zdb,title,creator,publisher,date,language,fullpath,year,month,day,issue,page,type,url
2887942,27913090,Berlinische Nachrichten von Staats- und gelehrten Sachen,,Berlin : Haude & Spener,1740-1872,ger,./publish/27913090_01/1832/02/02/01/presentation/27913090_1832-02-02_000_28_H_1_007.jpg,1832,02,02,1,7,jpg,https://content.staatsbibliothek-berlin.de/zefys/SNP27913090-18320202-0-7-0-0/full/full/0/default.jpg
2887943,27913090,Berlinische Nachrichten von Staats- und gelehrten Sachen,,Berlin : Haude & Spener,1740-1872,ger,./publish/27913090_01/1832/02/02/01/presentation/27913090_1832-02-02_000_28_H_1_012.jpg,1832,02,02,1,12,jpg,https://content.staatsbibliothek-berlin.de/zefys/SNP27913090-18320202-0-12-0-0/full/full/0/default.jpg
2887944,27913090,Berlinische Nachrichten von Staats- und gelehrten Sachen,,Berlin : Haude & Spener,1740-1872,ger,./publish/27913090_01/1832/02/02/01/presentation/27913090_1832-02-02_000_28_H_1_016.jpg,1832,02,02,1,16,jpg,https://content.staatsbibliothek-berlin.de/zefys/SNP27913090-18320202-0-16-0-0/full/full/0/default.jpg
2887945,27913090,Berlinische Nachrichten von Staats- und gelehrten Sachen,,Berlin : Haude & Spener,1740-1872,ger,./publish/27913090_01/1832/02/02/01/presentation/27913090_1832-02-02_000_28_H_1_004.jpg,1832,02,02,1,4,jpg,https://content.staatsbibliothek-berlin.de/zefys/SNP27913090-18320202-0-4-0-0/full/full/0/default.jpg
2887946,27913090,Berlinische Nachrichten von Staats- und gelehrten Sachen,,Berlin : Haude & Spener,1740-1872,ger,./publish/27913090_01/1832/02/02/01/presentation/27913090_1832-02-02_000_28_H_1_005.jpg,1832,02,02,1,5,jpg,https://content.staatsbibliothek-berlin.de/zefys/SNP27913090-18320202-0-5-0-0/full/full/0/default.jpg